<?php

use Illuminate\Database\Seeder;

class shiftsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shifts')->insert(
 
            [
              'date' => '2020-06-01',
              'start_time' => '09:00',
              'end_time' => '18:00',
              'rest_time' => '1:00',
              'total' => '8:00',
              'comments' => '最初の勤怠入力',
            //   'monthly_id' => '',
              'work_type_id' => '1',
              'user_id' => '1',
            
            // [
            //   'date' => '2020-06-02',
            //   'start_time' => '09:00',
            //   'end_time' => '18:00',
            //   'rest_time' => '1:00',
            //   'total' => '8:00',
            //   'comments' => '最初の勤怠入力',
            // //   'monthly_id' => '',
            //   'work_type_id' => '1',
            //   'user_id' => '1',
            // ],
            // [
            //   'date' => '2020-06-03',
            //   'start_time' => '09:00',
            //   'end_time' => '18:00',
            //   'rest_time' => '1:00',
            //   'total' => '8:00',
            //   'comments' => '最初の勤怠入力',
            // //   'monthly_id' => '',
            //   'work_type_id' => '1',
            //   'user_id' => '1',
            // ],
            //   [
            //     'date' => '2020-06-04',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-05',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-06',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-07',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-08',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-09',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-10',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-11',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-12',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-13',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-14',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-15',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-16',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-17',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-18',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-19',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-20',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-21',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-22',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-23',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-24',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-25',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-26',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-27',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-28',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-29',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],
            //   [
            //     'date' => '2020-06-30',
            //     'start_time' => '09:00',
            //     'end_time' => '18:00',
            //     'rest_time' => '1:00',
            //     'total' => '8:00',
            //     'comments' => '最初の勤怠入力',
            //     // 'monthly_id' => '',
            //     'work_type_id' => '1',
            //     'user_id' => '1',
            //   ],            
        //     [
        //       'date' => '2020-06-01',
        //       'start_time' => '09:00',
        //       'end_time' => '18:00',
        //       'rest_time' => '1:00',
        //       'total' => '8:00',
        //       'comments' => '最初の勤怠入力',
        //     //   'monthly_id' => '',
        //       'work_type_id' => '1',
        //       'user_id' => '2',
        //     ],
        //     [
        //       'date' => '2020-06-02',
        //       'start_time' => '09:00',
        //       'end_time' => '18:00',
        //       'rest_time' => '1:00',
        //       'total' => '8:00',
        //       'comments' => '最初の勤怠入力',
        //     //   'monthly_id' => '',
        //       'work_type_id' => '1',
        //       'user_id' => '2',
        //     ],
        //     [
        //       'date' => '2020-06-03',
        //       'start_time' => '09:00',
        //       'end_time' => '18:00',
        //       'rest_time' => '1:00',
        //       'total' => '8:00',
        //       'comments' => '最初の勤怠入力',
        //     //   'monthly_id' => '',
        //       'work_type_id' => '1',
        //       'user_id' => '2',
        //     ],
        //       [
        //         'date' => '2020-06-04',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-05',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-06',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-07',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-08',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-09',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-10',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-11',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-12',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-13',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-14',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-15',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-16',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-17',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-18',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-19',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-20',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-21',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-22',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-23',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-24',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-25',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-26',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-27',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-28',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-29',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-06-30',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],            
        //     [
        //       'date' => '2020-07-01',
        //       'start_time' => '09:00',
        //       'end_time' => '18:00',
        //       'rest_time' => '1:00',
        //       'total' => '8:00',
        //       'comments' => '最初の勤怠入力',
        //     //   'monthly_id' => '',
        //       'work_type_id' => '1',
        //       'user_id' => '1',
        //     ],
        //     [
        //       'date' => '2020-07-02',
        //       'start_time' => '09:00',
        //       'end_time' => '18:00',
        //       'rest_time' => '1:00',
        //       'total' => '8:00',
        //       'comments' => '最初の勤怠入力',
        //     //   'monthly_id' => '',
        //       'work_type_id' => '1',
        //       'user_id' => '1',
        //     ],
        //     [
        //       'date' => '2020-07-03',
        //       'start_time' => '09:00',
        //       'end_time' => '18:00',
        //       'rest_time' => '1:00',
        //       'total' => '8:00',
        //       'comments' => '最初の勤怠入力',
        //     //   'monthly_id' => '',
        //       'work_type_id' => '1',
        //       'user_id' => '1',
        //     ],
        //       [
        //         'date' => '2020-07-04',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-05',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-06',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-07',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-08',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-09',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-10',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-11',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-12',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-13',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-14',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-15',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-16',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-17',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-18',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-19',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-20',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-21',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-22',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-23',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-24',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-25',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-26',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-27',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-28',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-29',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],
        //       [
        //         'date' => '2020-07-31',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '1',
        //       ],            
        //     [
        //       'date' => '2020-07-01',
        //       'start_time' => '09:00',
        //       'end_time' => '18:00',
        //       'rest_time' => '1:00',
        //       'total' => '8:00',
        //       'comments' => '最初の勤怠入力',
        //     //   'monthly_id' => '',
        //       'work_type_id' => '1',
        //       'user_id' => '2',
        //     ],
        //     [
        //       'date' => '2020-07-02',
        //       'start_time' => '09:00',
        //       'end_time' => '18:00',
        //       'rest_time' => '1:00',
        //       'total' => '8:00',
        //       'comments' => '最初の勤怠入力',
        //     //   'monthly_id' => '',
        //       'work_type_id' => '1',
        //       'user_id' => '2',
        //     ],
        //     [
        //       'date' => '2020-07-03',
        //       'start_time' => '09:00',
        //       'end_time' => '18:00',
        //       'rest_time' => '1:00',
        //       'total' => '8:00',
        //       'comments' => '最初の勤怠入力',
        //     //   'monthly_id' => '',
        //       'work_type_id' => '1',
        //       'user_id' => '2',
        //     ],
        //       [
        //         'date' => '2020-07-04',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-05',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-06',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-07',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-08',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-09',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-10',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-11',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-12',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-13',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-14',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-15',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-16',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-17',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-18',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-19',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-20',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-21',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-22',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-23',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-24',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-25',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-26',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-27',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-28',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-29',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],
        //       [
        //         'date' => '2020-07-31',
        //         'start_time' => '09:00',
        //         'end_time' => '18:00',
        //         'rest_time' => '1:00',
        //         'total' => '8:00',
        //         'comments' => '最初の勤怠入力',
        //         // 'monthly_id' => '',
        //         'work_type_id' => '1',
        //         'user_id' => '2',
        //       ],            
        //     ]); 
        // }
        ]);
}
}