version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.2-apache-node-browsers
        environment:
        - DB_HOST=127.0.0.1
        - DB_PORT=3306
        - DB_DATABASE=sample_test
        - DB_USERNAME=circleci
        - DB_PASSWORD=circleci
      - image: circleci/mysql:5.7-ram
        environment:
        - MYSQL_ROOT_PASSWORD=circleci
        - MYSQL_DATABASE=sampe_test
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root3desu4
    steps:
      - checkout
  
      - run: sudo composer self-update --1
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
  
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
  
      - run: composer install -n --prefer-dist
  
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Test
          command: phpunit